spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
    import: secret/application-local.yml

---
spring:
  config:
    activate:
      on-profile: develop
    import: secret/application-develop.yml