spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coder_hive?serverTimezone=Asia/Seoul
    username: coderhive
    password: 3333
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
    open-in-view: false
  sql.init.mode: always

  servlet:
    multipart:
      max-file-size: 10000KB
      max-request-size: 10000KB